# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heat_transfer_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets  # type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 918)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.info_label = QtWidgets.QLabel(self.frame)
        self.info_label.setGeometry(QtCore.QRect(0, 0, 1001, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        self.info_label.setMinimumSize(QtCore.QSize(1000, 30))
        self.info_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.info_label.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.frame_11)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setEnabled(True)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.error_label_2 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label_2.sizePolicy().hasHeightForWidth())
        self.error_label_2.setSizePolicy(sizePolicy)
        self.error_label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.error_label_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.error_label_2.setObjectName("error_label_2")
        self.verticalLayout_5.addWidget(self.error_label_2)
        self.time_label_2 = QtWidgets.QLabel(self.frame_10)
        self.time_label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.time_label_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.time_label_2.setObjectName("time_label_2")
        self.verticalLayout_5.addWidget(self.time_label_2)
        self.horizontalLayout_7.addWidget(self.frame_10)
        self.button_run_3 = QtWidgets.QPushButton(self.frame_9)
        self.button_run_3.setMinimumSize(QtCore.QSize(0, 100))
        self.button_run_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(19, 255, 34);")
        self.button_run_3.setObjectName("button_run_3")
        self.horizontalLayout_7.addWidget(self.button_run_3)
        self.button_pause_3 = QtWidgets.QPushButton(self.frame_9)
        self.button_pause_3.setMinimumSize(QtCore.QSize(0, 100))
        self.button_pause_3.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.button_pause_3.setObjectName("button_pause_3")
        self.horizontalLayout_7.addWidget(self.button_pause_3)
        self.button_stop_3 = QtWidgets.QPushButton(self.frame_9)
        self.button_stop_3.setMinimumSize(QtCore.QSize(0, 100))
        self.button_stop_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.button_stop_3.setObjectName("button_stop_3")
        self.horizontalLayout_7.addWidget(self.button_stop_3)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.plot_area_3 = QtWidgets.QWidget(self.frame_4)
        self.plot_area_3.setMinimumSize(QtCore.QSize(0, 100))
        self.plot_area_3.setObjectName("plot_area_3")
        self.plot_area_layout_3 = QtWidgets.QVBoxLayout(self.plot_area_3)
        self.plot_area_layout_3.setContentsMargins(0, 0, 0, 0)
        self.plot_area_layout_3.setObjectName("plot_area_layout_3")
        self.verticalLayout_3.addWidget(self.plot_area_3)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1265, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.error_label_2.setText(_translate("MainWindow", "ERROR:"))
        self.time_label_2.setText(_translate("MainWindow", "TIME:"))
        self.button_run_3.setText(_translate("MainWindow", "RUN"))
        self.button_pause_3.setText(_translate("MainWindow", "PAUSE"))
        self.button_stop_3.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
